# Generated by Django 5.0.6 on 2024-05-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos/')),
                ('cover_photo', models.ImageField(blank=True, upload_to='cover_photos/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('comments', models.BooleanField(default=False)),
                ('candidates', models.BooleanField(default=False)),
                ('offers', models.BooleanField(default=False)),
                ('push_notifications', models.CharField(choices=[('everything', 'Everything'), ('same_as_email', 'Same as email'), ('nothing', 'No push notifications')], max_length=20)),
            ],
        ),
    ]
