# Generated by Django 5.0.6 on 2024-06-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_submitform'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSubmitForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(max_length=100, null=True)),
                ('accelerateLaunch', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('metadata', models.CharField(max_length=30, null=True)),
                ('folders', models.CharField(max_length=30, null=True)),
                ('datasetPreparation', models.CharField(max_length=30, null=True)),
                ('presets', models.CharField(max_length=30, null=True)),
                ('loraType', models.CharField(max_length=30, null=True)),
                ('networkWeights', models.CharField(max_length=50, null=True)),
                ('dimFromWeight', models.BooleanField(null=True)),
                ('trainBatchSize', models.CharField(max_length=30, null=True)),
                ('epoch', models.CharField(max_length=40, null=True)),
                ('maxTrainEpoch', models.CharField(max_length=30, null=True)),
                ('maxTrainStep', models.CharField(max_length=30, null=True)),
                ('saveEveryNEpochs', models.CharField(max_length=30, null=True)),
                ('captionFileExtension', models.CharField(max_length=30, null=True)),
                ('seed', models.CharField(max_length=30, null=True)),
                ('cacheLatent', models.CharField(max_length=30, null=True)),
                ('cacheLatentToDisk', models.CharField(max_length=30, null=True)),
                ('lrScheduler', models.CharField(max_length=30, null=True)),
                ('optimizer', models.CharField(max_length=30, null=True)),
                ('maxGradNorm', models.CharField(max_length=30, null=True)),
                ('lrSchedulerArg', models.CharField(max_length=30, null=True)),
                ('optimizerArg', models.CharField(max_length=30, null=True)),
                ('learningRate', models.CharField(max_length=30, null=True)),
                ('lrWarmup', models.CharField(max_length=30, null=True)),
                ('lrCycle', models.CharField(max_length=30, null=True)),
                ('lrPower', models.CharField(max_length=30, null=True)),
                ('maxResolution', models.CharField(max_length=30, null=True)),
                ('stopTE', models.CharField(max_length=30, null=True)),
                ('enableBuckets', models.CharField(max_length=30, null=True)),
                ('minBucketRes', models.CharField(max_length=30, null=True)),
                ('maxBucketRes', models.CharField(max_length=30, null=True)),
                ('textEncoderLR', models.CharField(max_length=30, null=True)),
                ('unetEncoderLR', models.CharField(max_length=30, null=True)),
                ('cacheTextEncoderOutput', models.CharField(max_length=30, null=True)),
                ('noHalfVAE', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
